language: node_js

node_js:
  - "9"

script: ./ci-cd/travis-testrpc.sh

cache:
  directories:
    - $HOME/.npm

#deploy:
  #- provider: script
    #skip_cleanup: true
    #script: ./ci-cd/deploy.sh kovan
    #on:
    #  branch: develop
